---
title: "Gruppavtal för grupp 10"
format: pdf
execute:
  echo: false
  r: true
  python: true
---

### Studieförutsättningar

Jacob Widaeus: Jag kommer arbeta på kursen under vardagskvällar. Dagtid till vardags arbetar jag. Jag har kunskap av R, git, python och statistik sedan tidigare.\
Karl Wärnberg: Jag kommer arbeta på vardagskvällar och helger. 21-28/9 (vecka 39) är jag bortrest. Jag har ingen erfarenhet av R, Git eller python. Jag har mycket begränsad erfarenhet av statistik och programmering. 
Rozh Kader:

### På vilket sätt vill vi hjälpas åt i studierna?

Vi vill hjälpas åt genom att regelbundet kommunicera och dela med oss av våra kunskaper och erfarenheter. Vi kan använda oss av gemensamma studiegrupper, där vi kan diskutera och lösa problem tillsammans. Vi kan också dela med oss av resurser och studiematerial som kan vara till nytta för alla i gruppen. Genom att hjälpa varandra kan vi öka förståelsen och effektiviteten i våra studier.

### Hur ska vi dela upp arbetet?

Vi ska dela upp arbetet genom att tilldela specifika uppgifter till varje gruppmedlem baserat på deras styrkor och intressen, och vid kvarvarande uppgifter kvar samarbetar vi för att slutföra dessa. Vi ämnar att arbetet utfört av respektive gruppindivid ska vara lika tidskrävande som andra medlemmars arbete.

### Vad ska vi göra om någon inte gör sin del av arbetet i tid?

Om någon inte gör sin del av arbetet i tid, ska vi först försöka förstå orsaken och erbjuda hjälp om det behövs. Om problemet kvarstår, kan vi diskutera det som en grupp och hitta en lösning tillsammans.

### På vilket sätt och hur ofta ska vi utvärdera hur arbetet i gruppen fungerar?

Vi ska utvärdera hur arbetet i gruppen fungerar genom regelbunden meddelandekontakt och ställvisa möten. Under dessa möten kan vi diskutera vad som fungerar bra och vad som kan förbättras.

### Finns det ytterligare regler vi bör ha i vår grupp?

-   

### Namnen på alla deltagare som bidragit till och godkänt kontraktet

```{python}
from datetime import datetime
print(datetime.now().strftime("%Y-%m-%d"))
```

Jacob Widaeus\
Karl Wärnberg\
Rozh Kader
